dist: xenial
language: node_js
node_js: [node]
cache: yarn
install: yarn install --no-lockfile
script: [yarn test, yarn ci-lint]
before_deploy: yarn version --no-git-tag-version --new-version "$TRAVIS_TAG"
deploy:
  provider: npm
  skip_cleanup: true
  email: ezzatron+iconduit@gmail.com
  api_key:
    secure: "esIYg1RydPT1/D3TAtW38V2Rj47ynt3ZeK9YLmzmZN3qDchCwVS0X/MHX25pjRzgv2hTrCtvmnnQ89nLo1faoyCge4mswk6LWEncg4LNhPl/z1Gb532IkgzrJIgAKzybS5weYnMvD7OMaH8vXh+k8AU8qlVSxW4V9KMHyeuXG7s8nnYXEEDDtTDiE016KCsc7+IgwLWVCTeI1dd877V+ux3Mr3hJG2IXAuO6+slnQEn4FMufYHVXlpogKhJwMEsJhvpUjIx4qTdHMMO07Xkr/KrU7t2z1QAbBlrwlpxNhg5jQcSQZvj7TiOneKA0OLbmO6boL0fuKmiIGPuoWE212Rv9QOC8bsbqOtx7y77x3pnpucqMCcRuNhmVwRmgLGaUWdfc/jxSRKdDNm8qphdV1WNqobhOFGTQTbBlWcJKQnbRyBvKfxFY5MhdbAOi08rXDko2zi3MLrbRK3eFb/HDRSXqztK5LbLuT9Vx26i78EPV7nVBwLGoSV35Nhq+CuRRZPm8hiNE0JynfckqYLKnQuxZNZ1h5o1uwSB01nhMwB0QCFoCN8gWqqozHtyCTwBR9mveyoJPaxi2N7dz5uAsB1wsdH1bCp9k/userc2ni8Vz7EHV7+dBzihyyIiFUgGqX1fpA0ZkioLe4lhwr0RNI3fwfwbKtiYBM7AIPUhnvjI="
  on:
    tags: true
